spring:
  application:
    name: system-service
  profiles:
    active: local

---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:system;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: true
  cloud:
    nacos:
      config:
        enabled: true
      discovery:
        enabled: true

app:
  jwt:
    secret: "dev-secret-dev-secret-dev-secret-32bytes!"
    expire-ms: 3600000

---
spring:
  config:
    activate:
      on-profile: nacos
