server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:nacos}

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        enabled: false

---
spring:
  config:
    activate:
      on-profile: nacos
    import: "nacos:${spring.application.name}.yaml"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: system-service
          uri: lb://system-service
          predicates:
            - Path=/api/system/**
        - id: biz-service
          uri: lb://biz-service
          predicates:
            - Path=/api/biz/**
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      discovery:
        namespace: ${NACOS_NAMESPACE:public}
      config:
        import-check:
          enabled: false
        namespace: ${NACOS_NAMESPACE:public}
        file-extension: yaml
