spring:
  application:
    name: gateway
  profiles:
    active: local

---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  cloud:
    nacos:
      config:
        enabled: true
      discovery:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: nacos
