server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: nacos

---
spring:
  config:
    activate:
      on-profile: nacos
    import: "nacos:${spring.application.name}.yaml"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: system-service
          uri: lb://system-service
          predicates:
            - Path=/api/system/**
        - id: biz-service
          uri: lb://biz-service
          predicates:
            - Path=/api/biz/**
    nacos:
      server-addr: 62.234.1.152:8848
      discovery:
        namespace: b66c93ce-3c83-4edd-a789-e3f47335c127
      config:
        import-check:
          enabled: false
        namespace: b66c93ce-3c83-4edd-a789-e3f47335c127
        file-extension: yaml
