server:
  port: 8082

spring:
  application:
    name: biz-service
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:biz;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: true
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        enabled: false

---
spring:
  config:
    activate:
      on-profile: nacos
    import: "nacos:${spring.application.name}.yaml"
  cloud:
    nacos:
      server-addr: 62.234.1.152:8848
      discovery:
        namespace: b66c93ce-3c83-4edd-a789-e3f47335c127
      config:
        import-check:
          enabled: false
        namespace: b66c93ce-3c83-4edd-a789-e3f47335c127
        file-extension: yaml
